config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/show'
  resources  :books
  resources  :shops,       only: [:index, :show]
  resources  :order_items
  resource   :cards,       only:[:show]

  devise_for :users

  root 'shops#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
    has_many    :order_items
    before_save :set_subtotal




    
    def subtotal
        order_items.collect {|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0}.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :book


    before_save :set_unit_price
    before_save :set_total


    def unit_price
        if persisted?
            self[:unit_price]
        else
            book.price
        end
    end

    def total
        unit_price*quantity
    end

    private

    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :price)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order = current_order
        @order_item = @order.order_items.new(order_params)
        @order.save
        session[:order_id] = @order.id
    end

    def update
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.update_attributes(order_params)
        @order_items = current_order.order_items
    end

    def destroy
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy
        @order_items = current_order.order_items
    end

    private

    def order_params
        params.require(:order_item).permit(:book_id, :quantity)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = Book.all
    @order_item = current_order.order_items.new
  end

  def show
    @book = Book.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/cards/_card.html.erb
<%= link_to cards_path do %>
    <i class="fal fa-shopping-cart fa-1x"></i> <%="Shopping Cart $#{current_order.subtotal}"%>
<% end %>

app/views/cards/_cards_item.html.erb
<h1>Reserved Books</h1>

<% @order_items.each do |item| %>
    <div class="card my-3">
        <h5 class="mt-3"><%= item.book.title %></h5>
        <p>$<%= item.book.price %></p>

        <%= form_for item, remote: true do |f| %>
            <%= f.hidden_field :book_id, :value => item.book.id %>
            <%= f.number_field :quantity, :value => item.quantity.to_i %>
            <%= f.submit 'Update', class: 'btn btn-info' %>

            <%= link_to 'Remove from Cart', order_item_path(item), method: :delete, remote: true, class: 'btn btn-danger' %>
        <% end %>

        <h5 class="mb-4">Subtotal: $<%= item.total %></h5>

    </div>
<% end %>

<h4>Total: $<strong><%= current_order.subtotal %></strong></h4>

app/views/cards/show.html.erb
<div id="card-item">
    <%= render 'cards/cards_item' %>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
    <%= render 'layouts/navbar_user' %>
<% else %>
    <%= render 'layouts/navbar_guess' %>
<% end %>

app/views/layouts/_navbar_guess.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">

  <a class="navbar-brand" href="/"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>

</div>
</nav>

app/views/layouts/_navbar_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">

  <a class="navbar-brand" href="/">Start</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%= link_to 'My Profile', cards_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%# Font Awesome %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>PortalLibros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/order_items/create.js.erb
$('#card').html('<%= j render 'cards/card' %>')

app/views/order_items/destroy.js.erb
$('#card').html('<%= j render 'cards/card' %>')
$('#card-item').html('<%= j render 'cards/cards_item' %>')

app/views/order_items/update.js.erb
$('#card').html('<%= j render 'cards/card' %>')
$('#card-item').html('<%= j render 'cards/cards_item' %>')

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Available Books</h1>

<div id="card" class="my-3">
  <%= render 'cards/card' %>
</div>

<table class="table table-borderless">
  <thead class="thead-light">
    <tr>
      <th>Book</th>
      <th>Price</th>
      <th>Details</th>
      <th>Reserve</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td>$<%= book.price %></td>
        <td><%= link_to 'View', shop_path(book) %></td>
        <td>
          <%= form_for @order_item, remote: true do |f| %>
            <%= f.hidden_field :book_id, :value => book.id %>
            <%= f.number_field :quantity, :value => 1, :min => 1 %>
            <%= f.submit 'Reserve', data: { disable_with: 'Processing...' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @book.price %>
</p>

<%= link_to 'Back', root_path %>